version: "3.1"

services:
  db:
    image: postgres:11.5
    restart: always
    environment:
      POSTGRES_PASSWORD: verysecure
    ports:
      - 3308:5432
    volumes:
      - esdcheck-db-data:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  esdcheck-db-data:
